### PR TITLE
updates audit rules list on readme

### PR DESCRIPTION
**Pull request by jaimeiniesta**
I've updated the audit rules list to what AccessLint is using currently.

Also, I've ordered the list alphabetically so that it's easier to maintain.

I would however start each one with its ID on the ADT wiki, like "AX_ARIA_01", so it's even clearer. If you wish, I'll add that.

### CODE REVIEW

**Comment by ckundo** [comment]
@jaimeiniesta do you think the error code will be useful, since they are specific to ADT? I'm ok either way, just lmk which you decide on and I'll merge.

**Comment by jaimeiniesta** [comment]
As AccessLint is a wrapper around ADT, I do think that the error code will be useful, so we can refer exactly to the rules we're taking into consideration.

If we just returned all the rules that ADT implements, I would just link to them and not repeat them again on this README. But as we're leaving some rules out, then I think it's best to mention exactly which ones we're including.

**Comment by ckundo** [comment]
That makes sense to me. Do you want to add those as part of this PR?

**Comment by jaimeiniesta** [comment]
Sure, I just added them and formatted the list as a table instead, I think it's much clearer now.

I wasn't sure about `AX_ARIA_02` though. The title from AccessLint does not match the title on ADT's wiki, can you verify that?

I think that having the exact codes will be also good to be able to link to its extended descriptions and examples of the good practices. In order to do that I want to investigate how to include them on the JSON results, but that's another story.

It's OK to merge if you wish.

**Comment by jaimeiniesta** [comment]
Also, if we ever get the audit rules translated to other languages, it will help to have a unique ID for each of them.

**Pull request merged**
